export enum authActions {
    SET_AUTH_USER_DATA = 'SET-AUTH-USER-DATA',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    SET_RESPONSE_ERROR = 'SET-RESPONSE-ERROR',
    SET_INITIALIZED_STATUS = 'SET-INITIALIZED-STATUS',
    SET_MY_DATA = 'SET-MY-DATA',
}

